### ISSUE TITLE
Launch new heroku test site

### ISSUE THREAD

**Issue by cranmer** [recast-hep/recast-flask-frontend#5]

**Comment by cranmer** [comment]
https://thawing-wildwood-30654.herokuapp.com/users

can we rename it?

**Comment by cbora** [comment]
I think so. Any suggestion?
Maybe [recast-hep.herokuapp.com]()

**Comment by cranmer** [comment]
:+1:

**Comment by lukasheinrich** [comment]
can you try recast-frontend, I just renamed mine so the URL should become free soon

**Comment by cbora** [comment]
Availabe on [recat-frontend.herokuapp.com](http://recast-frontend.herokuapp.com)
